services:
  - type: web
    name: brilink-tv-new
    env: node
    buildCommand: bun install && bun run build
    startCommand: bun run preview
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
