services:
  - type: web
    name: brilink-tv-new
    env: node
    buildCommand: npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
